### ISSUE TITLE
rml:languageMap returns an error

### ISSUE THREAD

**Issue by samiscoding** [carml/carml-jar#120]
Hi there,

I'm getting an error trying `rml:languageMap `. Here is a snippet following the provided [example](https://github.com/RMLio/RML-Processor/blob/05266b836857f3c528db7a134fa0b84559a34432/src/test/resources/exampleLanguageMap/thesaurus_XML.rml.ttl)

`<triplesMap>
	rml:logicalSource [
		rml:source "data.json" ;
		rml:referenceFormulation ql:JSONPath ;
		rml:iterator "$.list[*]" 
	] ;
	rr:subjectMap [
		rr:template "URI/{@.id}";
	] ;
    rr:predicateObjectMap [
        rr:predicate    skos:prefLabel;
        rr:objectMap    [
            rml:reference   "@.title";
            rml:languageMap    [
                rml:reference "@.lan"
            ]
        ]
    ].`

`{   
    "list": [
        {
    "id": "test-id",
    "title": "test-title",
    "lan": "en-us"
        }
    ]
}`

**Comment by pmaria** [comment]
Hi @samiscoding ,

Could you provide more details, e.g. an error message?

The example you point to seems different than the mapping excerpt you also describe. Could you provide an reproduction scenario in the form of input, and mapping?

**Comment by samiscoding** [comment]
Hi Pano,

Here is the error I have:

`java.lang.ClassCastException: class io.carml.model.impl.CarmlLanguageMap cannot be cast to class io.carml.model.ObjectMap (io.carml.model.impl.CarmlLanguageMap and io.carml.model.ObjectMap are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1a6c5a9e)`

and the reproducible mapping and data are attached as a zip.
[test-languageMap-carml.zip](https://github.com/carml/carml-jar/files/11331982/test-languageMap-carml.zip)

Can't find what I'm doing wrong here.

**Comment by pmaria** [comment]
Thanks, I will take a look this week.

**Comment by pmaria** [comment]
Fixed since CARML 4.8.0 and in the latest CARML-jar release
