### ISSUE TITLE
Multivalued input parameters in RML Functions.

### ISSUE THREAD

**Issue by joseph6x** [carml/carml-jar#155]
Hi.

I would like to apply a RML Function to each item of an array in JSON.
Basically I have an field in JSON that contains an array:
```json
{   
    "list": [
        {
            "id": "test-id",
            "array": [ "a/1", "a/2" ]
        }
    ]
}
```

And, I want to replace the character '/' with '-' in the RDF output. I tried to implement this behavior using the following RML Function and mapping.

Function:
```java 
 @FnoFunction("urn:replace")
    public String replace(String prefix, @FnoParam("urn:input") String input, @FnoParam("urn:search") String search, @FnoParam("urn:replace") String replace) {
      if (input == null) {
         return null;
      }
      return input.replaceAll(search, replace);
    }
```

RML:
```turtle
    rr:predicateObjectMap [
        rr:predicate    <urn:property>;
        rr:objectMap    [
			fnml:functionValue [
				rml:logicalSource [] ;
				rr:subjectMap [
					rr:template "functionExec" ;
					rr:termType rr:BlankNode ;
					rr:class fno:Execution ;
				] ;
				rr:predicateObjectMap
					[
						rr:predicate fno:executes ;
						rr:object <urn:replace> ;
					],
					[
						rr:predicate <urn:input> ;
						rr:objectMap [ rml:reference "@.array" ]
					],
					[
						rr:predicate <urn:search> ;
						rr:objectMap [ rr:constant "/" ]
					],
					[
						rr:predicate <urn:replace> ;
						rr:objectMap [ rr:constant "-" ]
					]
			]
        ]
    ]
```
However, the RML Functions seem to accept only parameters with one single value, and not accept arrays because I get this error when I execute the conversion:

`java.lang.IllegalArgumentException: value [["a/1", "a/2"]] has more than one value, which is not expected.`

Is this an expected behavior or is there a workaround to implement this?.

Thanks in advance for your help.

**Comment by pmaria** [comment]
Hi @joseph6x,

Somehow I have missed this issue completely and only now noticed it 😢. My sincere apologies. 

What happens here is that you're passing an array to a string parameter.
In this case you can declare define the function with a `List<String>` parameter to accept the input, and  handle the list in the function itself. If you want to return multiple values you can also make the function return a list.

So, in this case you can write your function like this:

```java
  @FnoFunction("urn:replace")
  public List<String> replace(@FnoParam("urn:input") List<String> inputs, @FnoParam("urn:search") String search, @FnoParam("urn:replace") String replace) {
    if (inputs == null) {
      return List.of();
    }
    
    return inputs.stream()
        .map(input -> input.replaceAll(search, replace))
        .collect(Collectors.toList());
  }
```

Sorry again for the late response. Hope this still helps.

Please close the issue if this solves the issue for you.

**Comment by joseph6x** [comment]
Thanks @pmaria  it solves the issue for me.
