### ISSUE TITLE
Support for stdin

### ISSUE THREAD

**Issue by pmaria** [carml/carml-jar#47]
Add support for stdin. This will require a mapping to make use of [CARML's input stream extension](https://github.com/carml/carml#input-stream-extension)

**Comment by pmaria** [comment]
@tobiasschweizer FYI

**Comment by tobiasschweizer** [comment]
Thanks, let me know if /  when you need a guinea pig to test this ... :-)

**Comment by tobiasschweizer** [comment]
I can confirm that it works for me :-)

- I rebuilt t the project and used ` carml-jar-1.0.0-SNAPSHOT-0.4.4.jar`
- I used `carml:Stream` in my mapping's logical sources
- I redirected the data input file using `<`

The only thing I found is a typo: "CARML input stream **exentsion**" -> extension (https://github.com/carml/carml-jar#using-stdin)

**Comment by pmaria** [comment]
Cool! Thanks for catching the typo

**Comment by tobiasschweizer** [comment]
The least I could do :-)

I actually wanted to look at the [templating support](https://github.com/carml/carml-jar/issues/10) we talked about but unfortunately I was unable to find time for it so far ...
