### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ktk** [carml/carml-jar#51]
I see there are some Github actions but I don't see releases, could those be made available as well?

**Comment by pmaria** [comment]
yes, i will publish a first release by the end of next week

**Comment by ktk** [comment]
Excellent thanks! FWIW I built a version and successfully used it in some mappings.

**Comment by pmaria** [comment]
@ktk finally got around to organizing the release.

**Comment by ktk** [comment]
@pmaria thanks a lot!
