### ISSUE TITLE
Support specification of namespaces for output

### ISSUE THREAD

**Issue by pmaria** [carml/carml-jar#6]
To generate output with prefixed IRIs we need to support specifying custom prefixes.

Possible Approaches:

## prefixes via single CLI option
A simple way of providing namespace prefixes would be providing as an option. 

For example a list of strings wherin we alternate for prefix and name:

```
-p ex http://example.com/ foaf http://xmlns.com/foaf/0.1/
```

Or add a separator `:` between prefix and name:

```
-p ex:http://example.com/ foaf:http://xmlns.com/foaf/0.1/
```

Pros: 
* simple to use and implement.

Cons:
* having to define the prefixes on every run. 
* with a lot of prefixes this is a pain.

## prefixes as JSON-LD context

Antoher way would be to support providing a JSON-LD context which contains the namespace prefix definitions. An additional benefit here is that we could use the [latest prefix.cc context](https://prefix.cc/context) as a default set of prefixes that are available.

We could then introduce two options:
* `-c`  `-pc`  `--prefix-context` - path to JSON-LD Context file containing available namespace definitions. If left empty will default to [prefix.cc](https://prefix.cc/) context https://prefix.cc/context 
* `-p` `--prefixes`  prefixes from provided namespace JSON-LD context file to apply. (see -c)

With regards to aquiring the context at https://prefix.cc/context, the easiest approach would be to package it with the app, and update it on every new release, with the obvious downside of up-to-dateness.
The other option is to fetch it and cache it somehow, but I think this is too complicated for now.

Pros:
* simple to use
* define one context, reuse it in all your mappings

Cons:
* if we go the live-fetching way, more difficult to implement and possibly use, due to networking issues.
* if we go the locally packaged way, up-to-dateness. However, one can always download the newest version and store it locally and refer to it via `-c`.

**Comment by pmaria** [comment]
@tobiasschweizer @semanticfire I'd appreciate your input on this.

**Comment by tobiasschweizer** [comment]
If I understand correctly you are thinking about the best way to pass in prefix defs. to be applied to the serialised output graph from the command line.

Here are some questions / remarks:
- if the prefixes are provided as a JSON-LD context, this would also take effect for all serialisation formats beside JSON-LD, i.e. Turtle, N-Triples and the like? Maybe in this case the JSON-LD context object would seem like an odd way to someone only familiar with Turtle.
- I understand the idea of a fallback JSON-LD context object, however, considering schema.org, I made kind of a painful experience with what happened in `rdflib`: `schema` now refers to `https://schema.org` while the non TLS version is now called `schema1`. If someone builds an application that is not RDF aware this could lead to surprises as the fallback context evolves over time.

Since mapping to RDF and defining the prefixes of the serialised output graph seem like two steps, would it be possible to keep the APIs somehow separate? I have noticed that for the jar there is a `map` command, so could the output somehow be piped into another command like in `bash` (obviously without calling the jar twice)?

**Comment by pmaria** [comment]
> If I understand correctly you are thinking about the best way to pass in prefix defs. to be applied to the serialised output graph from the command line.

Correct.

> Here are some questions / remarks:
> 
> * if the prefixes are provided as a JSON-LD context, this would also take effect for all serialisation formats beside JSON-LD, i.e. Turtle, N-Triples and the like? 

Yes indeed. The context would serve purely as a prefix mapping, irrespective of the output RDF format.

> Maybe in this case the JSON-LD context object would seem like an odd way to someone only familiar with Turtle.

Yes maybe. Another more neutral option would be to have a YAML prefix map. Something like:

```yaml
namespaces:
  foo: http://foo.com/
  bar: http://bar.org/
```

Although I like the idea of supporting the prefix.cc format. We could also support both.

> * I understand the idea of a fallback JSON-LD context object, however, considering schema.org, I made kind of a painful experience with what happened in `rdflib`: `schema` now refers to `https://schema.org` while the non TLS version is now called `schema1`. If someone builds an application that is not RDF aware this could lead to surprises as the fallback context evolves over time.

True. But then those that require that stability can keep their own managed copy locally and pass that as the prefix context.


> Since mapping to RDF and defining the prefixes of the serialised output graph seem like two steps, would it be possible to keep the APIs somehow separate? I have noticed that for the jar there is a `map` command, so could the output somehow be piped into another command like in `bash` (obviously without calling the jar twice)?

They aren't actually that separate, especially not when pretty printing. Piping it would be a needless I/O step IMO. 

Are your concerns on the usability of the interface? 

A basic working command could be:

`carml map -m mapping.ttl -p ex foo bar `

**Comment by tobiasschweizer** [comment]
> They aren't actually that separate, especially not when pretty printing. Piping it would be a needless I/O step IMO.

Yes, sorry, I did not express that thought very well. What I meant was rather using the commands to keep APIs separate for mapping and formatting, e.g., `carml map -m mapping.ttl format -p ex foo bar`

Everything related to serialisation could be left to `format`.

Not sure if that is feasible, but it would allow for usage instructions for mapping and formatting without mixing them in the usage instructions. 

I am not Java expert or familiar with the Spring framework, but this somehow seemed interesting:

> Missing required subcommand
Usage: carml [-hV] [COMMAND]
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  map

So there could be more commands than map. However, the `format` command would not make sense without a previous `map` so I am not sure whether my idea is actually useful ;-)

**Comment by pmaria** [comment]
Ah right. I don't think it's possible, due to exactly as you say

>However, the format command would not make sense without a previous map

I'm using [picocli](https://picocli.info/) for the CLI implementation, and the idea seems to be that every command or subcommand is executable separately. But I'll have a look if there is a possibility there.

**Comment by pmaria** [comment]
@tobiasschweizer I took a look at the possibilities of [picocli](https://picocli.info/), but a subcommand like this is not possible, since it would need to have a separate execution path from a plain `map` call.

What is possible is an option with nested sub-options.

Sou you could do something like: 
```console
carml map \
  -m mapping \
  --format-output \
    -of ttl \
    -p ex foo bar
```

But I'm doubting how useful that really is. I'm leaning towards keeping it a flat list of options.

**Comment by tobiasschweizer** [comment]
@pmaria Thanks for checking. I guess since there are not many options a flat list is ok :-)

**Comment by semanticfire** [comment]
I have to admit I haven't thought about this, I'm allergic to yaml, and it is _alien_ format in the RDF world.
Why not add the prefixes in the mapping?

**Comment by tobiasschweizer** [comment]
> it is _alien_ format in the RDF world.

What is your opinion on [YARRRML](https://rml.io/yarrrml/) then? ;-)

**Comment by pmaria** [comment]
@semanticfire 
> Why not add the prefixes in the mapping?

I assume you mean: take the prefixes declared in the mapping(s) and then use those in the output.

Some issues with that:
* Would need to implement this per serialization, which is not trivial to do because in some serializations prefix declarations can be done anywhere in the document
* RDF4J does not provide utilities for namespace preservation when parsing (as far as I know), probably for the above reason, so would have to implement this ourselves per serialization.
* Would probably lead to useless prefix declarations, e.g. `rml`, `rr`, `fno` etc.
* Would possibly miss prefix declarations for IRIs that are created via expressions like `rr:template`

**Comment by semanticfire** [comment]
I was more thinking of a solution like this:
https://www.w3.org/TR/shacl/#sparql-prefixes

**Comment by tobiasschweizer** [comment]
> I was more thinking of a solution like this: https://www.w3.org/TR/shacl/#sparql-prefixes

So this would be expressed as RDF, ie. within the mapping?

**Comment by semanticfire** [comment]
Yup, not reliant on the actual serialization of the mapping, but explicitly expressed in RDF

**Comment by pmaria** [comment]
> I was more thinking of a solution like this: https://www.w3.org/TR/shacl/#sparql-prefixes

As discussed, I prefer not to create any new vocabulary since it is not standard and has to remain supported.

As this seems like something that could be added to RML itself, I will open an issue over at https://github.com/kg-construct/dataio-spec to discuss that.
