### ISSUE TITLE
Organize output

### ISSUE THREAD

**Issue by pmaria** [carml/carml-jar#8]
Issue to track the organization of console output.

- [x] Map all exceptions to specific error codes
- [x] By default output RDF output only to stdout
- [x] Introduce verbose options (`-v(vv)` `--verbose`) to output additional logging
- [x] Log errors to stderr

**Comment by tobiasschweizer** [comment]
If I may: Could `-q` and `-v` be thought of as mutually exclusive options? 
My personal preference would be a default of RDF output only with the option of additional output for debugging, i.e. `-v`.

**Comment by pmaria** [comment]
Hmm yeah, I was doubting which route to take here. Could you elaborate on why that would be your preference?

**Comment by tobiasschweizer** [comment]
Sure :-) I think it is primarily a question of convenience: if everything goes well (exit code 0), the output graph is written to `stdout` without any further logging output or configuration flags needed. 
In my workflow, I control things with Python subprocesses and directly continue with what `stdout` returns.

If the output seems strange (although the engine did not throw an error), then I would further investigate with `-v` to see what happened.

I think in case of a non 0 exit code, it would be convenient to directly write an error message to `sdterr`. Not sure if there could be categories of errors like things done wrong by the user (syntactically invalid Turtle, missing things in the mapping etc.) or things that the engine cannot process properly for some reason. I am primarily familiar with REST APIs and there you have categories which indicate that something was the user's fault or things like internal server errors expressed with HTTP status codes.

It might also be worth looking at https://github.com/RMLio/rmlmapper-java#cli. 

For me, having two implementations available to process my RML mappings with is a real plus, especially if their APIs are quite similar (it makes it easier to exchange one for the other in your workflow).

**Comment by tobiasschweizer** [comment]
If you like, I'd be open for a short call this week to discuss this. Maybe also with @semanticfire? He also made a WAR file which I find useful.

**Comment by pmaria** [comment]
> Sure :-) I think it is primarily a question of convenience: if everything goes well (exit code 0), the output graph is written to `stdout` without any further logging output or configuration flags needed. In my workflow, I control things with Python subprocesses and directly continue with what `stdout` returns.
> 
> If the output seems strange (although the engine did not throw an error), then I would further investigate with `-v` to see what happened.

Cool. I just wonder if this will be true for the majority of users. But I guess it is simple enough to add `-v(vv)` for more verbosity. 

> I think in case of a non 0 exit code, it would be convenient to directly write an error message to `sdterr`. Not sure if there could be categories of errors like things done wrong by the user (syntactically invalid Turtle, missing things in the mapping etc.) or things that the engine cannot process properly for some reason. I am primarily familiar with REST APIs and there you have categories which indicate that something was the user's fault or things like internal server errors expressed with HTTP status codes.

Yeah idea would be to have error codes for specific errors and have the message output to sterr.
> 
> It might also be worth looking at https://github.com/RMLio/rmlmapper-java#cli.

I'll take a look.

> For me, having two implementations available to process my RML mappings with is a real plus, especially if their APIs are quite similar (it makes it easier to exchange one for the other in your workflow).

**Comment by pmaria** [comment]
> If you like, I'd be open for a short call this week to discuss this. Maybe also with @semanticfire? He also made a WAR file which I find useful.

Sounds good. I'm available this week.

**Comment by tobiasschweizer** [comment]
> Sounds good. I'm available this week.

Great, what about Wednesday or Thursday afternoon at 14h?

**Comment by pmaria** [comment]
Both times work for me

**Comment by tobiasschweizer** [comment]
Great, I've sent you an invite for tomorrow!
